# fly.toml file generated for htlchat on 2023-03-29T20:12:36-05:00

app = "htlchat"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "iad"
processes = []

[build]
  [build.args]
    NEXT_PUBLIC_EXAMPLE = "Value goes here"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
